
FROM fluent/fluentd

# Add your kibana plugins setup here
# Example: RUN fluent-gem install fluent-plugin-elasticsearch
RUN fluent-gem install fluent-plugin-elasticsearch
RUN fluent-gem install fluent-plugin-secure-forward
